apiVersion: v1
kind: Service
metadata:
  name: {{ include "regret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regret.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "regret.selectorLabels" . | nindent 4 }}
